name: Deploy Bot

on:
  push:
    branches:
      - main  # Этот процесс срабатывает на push в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Убедитесь, что у вас есть requirements.txt с зависимостями

    - name: Deploy the app (Gunicorn + Nginx)
      run: |
        sudo apt update
        sudo apt install -y nginx
        sudo apt install -y gunicorn
        gunicorn --bind 127.0.0.1:8000 bot:app  # Запуск приложения через Gunicorn
        sudo service nginx restart  # Перезапуск Nginx
